# Generated by Django 2.0.4 on 2018-12-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vendor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='email',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='password',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='reset_password',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='route',
        ),
    ]
