# Generated by Django 2.0.4 on 2018-12-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181226_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='route',
            field=models.CharField(default='route 1', max_length=200),
            preserve_default=False,
        ),
    ]
