# Generated by Django 2.0.4 on 2018-11-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181112_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=200)),
                ('discount_persentage', models.CharField(blank=True, max_length=200)),
                ('is_active', models.CharField(max_length=1)),
            ],
        ),
    ]
