# Generated by Django 2.0.4 on 2018-11-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax_collected',
            new_name='total_tax',
        ),
    ]
