# Generated by Django 2.0.4 on 2018-11-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20181112_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='final_price',
            new_name='total_price',
        ),
    ]
