# Generated by Django 2.0.4 on 2018-12-18 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_vendor_image'),
        ('orders', '0008_coupon_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.DeliveryBoy'),
        ),
    ]
