# Generated by Django 2.0.4 on 2018-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_boy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trasaction_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
