# Generated by Django 2.0.4 on 2018-10-14 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('is_active', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('is_active', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('is_veg', models.CharField(max_length=1)),
                ('is_active', models.CharField(max_length=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Cuisine')),
            ],
        ),
    ]
